### PR TITLE
travis: update go version

### PR DESCRIPTION
**Pull request by dvrkps**

### CODE REVIEW

**Comment by dvrkps** [comment]
@davecheney ping :)

**Comment by davecheney** [comment]
This PR doesn’t pass. I haven’t looked into the reasons why.

**Comment by dvrkps** [comment]
@davecheney 
build log says: "The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over)."

latest three builds from a year ago are broken too.
Can/May i close this ?

**Comment by davecheney** [comment]
kodos is just an experiment. I don't have any bandwidth to look at the failing tests at the moment. Sorry.

**Comment by dvrkps** [comment]
@davecheney np. I close this. Thx. Stay cool :)

**Pull request closed without merging**
